// This file was automatically generated by Bunli.
// You should NOT make any changes in this file as it will be overwritten.

import type { Command, CLI, GeneratedOptionMeta, RegisteredCommands, CommandOptions, GeneratedCommandMeta } from '@bunli/core'
import { createGeneratedHelpers, registerGeneratedStore } from '@bunli/core'

import Deploy from '../src/commands/deploy.js'
import Greet from '../src/commands/greet.js'
import Hello from '../src/commands/hello.js'

// Narrow list of command names to avoid typeof-cycles in types
const names = ['deploy', 'greet', 'hello'] as const
type GeneratedNames = typeof names[number]

const modules: Record<GeneratedNames, Command<any>> = {
  'deploy': Deploy,
  'greet': Greet,
  'hello': Hello
} as const

const metadata: Record<GeneratedNames, GeneratedCommandMeta> = {
  'deploy': {
      name: 'deploy',
      description: '',
      options: {
        'env': { type: 'z.enum', required: true, hasDefault: false, description: 'Target environment', enumValues: ["dev","staging","prod"], schema: {"type":"zod","method":"enum","args":[{"type":"unknown","raw":{"type":"ArrayExpression","start":231,"end":257,"loc":{"start":{"line":10,"column":19,"index":231},"end":{"line":10,"column":45,"index":257}},"elements":[{"type":"StringLiteral","start":232,"end":237,"loc":{"start":{"line":10,"column":20,"index":232},"end":{"line":10,"column":25,"index":237}},"extra":{"rawValue":"dev","raw":"'dev'"},"value":"dev"},{"type":"StringLiteral","start":239,"end":248,"loc":{"start":{"line":10,"column":27,"index":239},"end":{"line":10,"column":36,"index":248}},"extra":{"rawValue":"staging","raw":"'staging'"},"value":"staging"},{"type":"StringLiteral","start":250,"end":256,"loc":{"start":{"line":10,"column":38,"index":250},"end":{"line":10,"column":44,"index":256}},"extra":{"rawValue":"prod","raw":"'prod'"},"value":"prod"}]}}]}, validator: '(val) => true' }
      },
      path: './src/commands/deploy'
    },
  'greet': {
      name: 'greet',
      description: 'Greet someone',
      options: {
        'name': { type: 'z.string.min', required: true, hasDefault: false, description: 'Name to greet', short: 'n', min: 1, minLength: 1, schema: {"type":"zod","method":"min","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":225,"end":226,"loc":{"start":{"line":9,"column":27,"index":225},"end":{"line":9,"column":28,"index":226}},"extra":{"rawValue":1,"raw":"1"},"value":1}}]}, validator: '(val) => true' },
        'excited': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Add excitement', short: 'e', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":361,"end":366,"loc":{"start":{"line":13,"column":39,"index":361},"end":{"line":13,"column":44,"index":366}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/greet'
    },
  'hello': {
      name: 'hello',
      description: 'Say hello to someone',
      options: {
        'name': { type: 'z.string.default', required: true, hasDefault: true, default: "World", description: 'Name to greet', short: 'n', schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"World"}]}, validator: '(val) => true' },
        'excited': { type: 'z.boolean.default', required: true, hasDefault: true, default: false, description: 'Add excitement!', short: 'e', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":364,"end":369,"loc":{"start":{"line":16,"column":26,"index":364},"end":{"line":16,"column":31,"index":369}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/hello'
    }
} as const

export const generated = registerGeneratedStore(createGeneratedHelpers(modules, metadata))

export const commands = generated.commands
export const commandMeta = generated.metadata

export interface GeneratedCLI {
  register(cli?: CLI<any>): GeneratedCLI
  list(): Array<{
    name: GeneratedNames
    command: (typeof modules)[GeneratedNames]
    metadata: (typeof metadata)[GeneratedNames]
  }>
  get<Name extends GeneratedNames>(name: Name): (typeof modules)[Name]
  getMetadata<Name extends GeneratedNames>(name: Name): (typeof metadata)[Name]
  getFlags<Name extends keyof RegisteredCommands & string>(name: Name): CommandOptions<Name>
  getFlagsMeta<Name extends GeneratedNames>(name: Name): Record<string, GeneratedOptionMeta>
  withCLI(cli: CLI<any>): { execute(name: string, options: unknown): Promise<void> }
}

export const cli: GeneratedCLI = {
  register: (cliInstance?: CLI<any>) => { generated.register(cliInstance); return cli },
  list: () => generated.list(),
  get: <Name extends GeneratedNames>(name: Name) => generated.get(name),
  getMetadata: <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name),
  getFlags: <Name extends keyof RegisteredCommands & string>(name: Name) => generated.getFlags(name) as CommandOptions<Name>,
  getFlagsMeta: <Name extends GeneratedNames>(name: Name) => generated.getFlagsMeta(name),
  withCLI: (cliInstance) => generated.withCLI(cliInstance)
}

// Enhanced helper functions
export const listCommands = () => generated.list().map(c => c.name)
export const getCommandApi = <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name)
export const getTypedFlags = <Name extends GeneratedNames>(name: Name) => generated.getFlags(name) as CommandOptions<Name>
export const validateCommand = <Name extends GeneratedNames>(name: Name, flags: Record<string, unknown>) => generated.validateCommand(name, flags)
export const findCommandByName = <Name extends GeneratedNames>(name: Name) => generated.findByName(name)
export const findCommandsByDescription = (searchTerm: string) => generated.findByDescription(searchTerm)
export const getCommandNames = () => generated.getCommandNames()

// Auto-register on import for zero-config usage
export default cli

// Ensure module augmentation happens on import
declare module '@bunli/core' {
  // Precise key mapping without typeof cycles
  interface RegisteredCommands extends Record<GeneratedNames, Command<any>> {}
}
